### PR TITLE
Add notification on playback error

### PR DESCRIPTION
**Pull request by felixheidecke**
Add notification if video playback fails.

Bildschirmfoto 2019-08-28 um 10 57 37

Fixes https://github.com/owncloud/files_mediaviewer/issues/35

### CODE REVIEW

**Comment by davitol** [comment]
👎 @felixheidecke I cannot get the new notification:

Tests steps from https://github.com/owncloud/files_mediaviewer/issues/35#issue-409263350 and Chrome for Mac Version 76.0.3809.100


Console error was spotted
```
{"reqId":"Hg7vNxNHyim8Bwh8FJHr","level":2,"time":"2019-08-28T10:05:29+00:00","remoteAddr":"172.21.0.1","user":"admin","app":"no app in context","method":"GET","url":"\/remote.php\/webdav\/big.mp4","message":"File with name big.mp4 could not be located"}
```

**Comment by felixheidecke** [comment]
are you sure you compiled? Becauuuuuse … the console error is from … before :-P

Works with FF and Chrome

**Comment by davitol** [comment]
@felixheidecke Retested and keeps not working for me.

Screen Shot 2019-08-29 at 09 28 19


And I get the log:

```
{"reqId":"Lm5BlUXvGKJyzugb5zHG","level":2,"time":"2019-08-29T07:27:54+00:00","remoteAddr":"172.18.0.1","user":"admin","app":"no app in context","method":"GET","url":"\/remote.php\/webdav\/big2.mp4","message":"File with name big2.mp4 could not be located"}
```

**Comment by felixheidecke** [comment]
@davitol looks like I forgot to add this notification for images as well 😅

**Comment by felixheidecke** [comment]
@davitol can you have another look? I think that'll fix it.

**Comment by felixheidecke** [comment]
@davitol ping

**Comment by mmattel** [comment]
Ping... any progress ?

**Comment by davitol** [comment]
Tested and LGTM

**Comment by davitol** [comment]
BTW  Warning **Fail to load video data** has no translation

**Pull request merged**
