### PR TITLE
add app icon

### PR DESCRIPTION
**Pull request by hurradieweltgehtunter**
In addition to the new app images the icons get updated, too.
@mmattel @pmaier1

### CODE REVIEW

**Comment by michaelstingl** [comment]
> In addition to the new app images the icons get updated, too.
> @mmattel @pmaier1

Where is this icon shown? Marketplace? In ownCloud server web UI? Screenshot?

**Comment by hurradieweltgehtunter** [comment]
Icon is shown in the app overview in ownCloud web UI.

**Comment by pmaier1** [comment]
Screenshot from 2019-03-14 10-27-51

^ This is the design of oC 10 app icons. Thanks for the icons but I see no benefit in changing this right now. I rather think that the colored icons won't match the overall design, especially when some are in old and some in new design which would be the case until all apps (consider community apps!) have updated logos. Sorry, but I won't accept this.

**Comment by hurradieweltgehtunter** [comment]
icon removed
screenshot updated 
@pmaier1

**Comment by pmaier1** [comment]
Nice, thanks. I already added it here https://github.com/owncloud/files_mediaviewer/pull/63

**Pull request closed without merging**
