### PR TITLE
[RC 1.0.0] Reset store on deactivation

### PR DESCRIPTION
**Pull request by felixheidecke**
Reset the store contents when deactivating the swiper.

Fixes: #74
Fixes: #75
Fixes: #76
Fixes: #77

### CODE REVIEW

**Comment by skshetry** [comment]
I feel that this solves #75, #76, #77 (at least, I did not encounter). We can do  full testplan on release. But, the play button is not disappearing for me.

### Steps to reproduce:
1. Have 2,3 videos inside a folder.
2. Open the top media file that is supported from the listing.
3. Play. The pause button should disappear.
4. Play any media file other than the top one. The pause button does not disappear.
5. Change the order of the media files (through sorting: size or datetime).
6. Play the top media file. The pause button disappears.
7. Play any media file other than the top one. The pause button does not disappear.

You get weird errors some of the times. When I click a video and click play button just after opening the viewer, I get following error (after waiting for a sec and clicking play button doesnot throw this error):
```
TypeError: this.$video.pause is not a function
    at a.togglePlay (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:3552:17)
    at click (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:3686:461)
    at He (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:4059:11384)
    at HTMLButtonElement.n (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:4059:13168)
    at HTMLButtonElement.Yr.o._wrapper (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:4059:48505)
```

Some of the times, on clicking the file row, I get following error (though, it seemed fine):
```
VM715:4059 TypeError: Cannot read property 'addEventListener' of undefined
    at a.init (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:3619:19)
    at wn.eval (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:3631:11)
    at He (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:4059:11384)
    at wn.e.$emit (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:4059:34373)
    at h.slideChangeTransitionEnd (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:3146:17)
    at eval (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:4042:15599)
    at Array.forEach (<anonymous>)
    at eval (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:4042:15577)
    at Array.forEach (<anonymous>)
    at h.n.emit (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:4042:15449)
```

Opening video player too many times, I could break the viewer. I'd get following error on console.
```
VM715:4059 TypeError: Cannot read property 'mimetype' of undefined
    at itemType (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:3933:31)
    at wrappedGetter (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:2656:12)
    at wn.computed.<computed> (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:2456:42)
    at fn.get (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:4059:26768)
    at fn.evaluate (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:4059:27918)
    at wn.eval [as itemType] (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:4059:29822)
    at Object.get [as itemType] (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:2458:42)
    at a.slideIsVideo (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:3282:31)
    at fn.get (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:4059:26768)
    at fn.evaluate (eval at globalEval (jquery.min.js?v=94bf5e37a1c47c91910eca20ff98bb9d:1), <anonymous>:4059:27918)
```
Screenshot from 2019-06-14 12-28-20

**Comment by micbar** [comment]
@felixheidecke Is this PR ready?

**Comment by micbar** [comment]
@felixheidecke Did you fix the errors discovered in https://github.com/owncloud/files_mediaviewer/pull/84#issuecomment-501989347

**Comment by skshetry** [comment]
@micbar. as per the discussion with @felixheidecke, 
6aa455b and 91fc3de solves the issues. I tested this on Chrome, and Firefox, and I no longer have the issues.

**Pull request merged**
