### PR TITLE
Move from grunt to webpack

### PR DESCRIPTION
**Pull request by felixheidecke**
Closes: https://github.com/owncloud/files_mediaviewer/issues/91

### CODE REVIEW

**Comment by felixboehm** [comment]
looks good, not tested.
@felixheidecke did you test a build? 
Is this app having its own vue instance? That a good idea?
We agreed on finding a solution to provide a central instance and have apps just add a component. Any progress into this direction?

**Comment by DeepDiver1975** [comment]
> We agreed on finding a solution to provide a central instance and have apps just add a component.

Unless I totally missed some discussions/agreements in the past: the single vue instance is a concept we are driving in phoenix. For OC10 this wold result in a too big change to the codebase from my understanding because as of today each of the oc10 apps with vue just ship their own set of libs and bootstrep themselves as needed.

**Comment by felixheidecke** [comment]
> did you test a build?

@felixboehm I did and it looks good on my side, but waiting for a reply from @davitol to confirm its working 👍 

> Is this app having its own Vue instance?

As @DeepDiver1975 mentioned, there is no single instance approach for OC10 apps. My orders are to "waste" as little time on OC10 frontend as possible ;-)

**Comment by davitol** [comment]
@felixheidecke Make dist  fails for me.

**Module not found: Error: Can't resolve './geteventlisteners'** I guess geteventlisteners is case Sensitive

```
$ webpack -p
Hash: 3fbd47299aef054b59221e505e8bbd08b28b1357
Version: webpack 4.38.0
Child app:
    Hash: 3fbd47299aef054b5922
    Time: 13751ms
    Built at: 2019-08-01 07:26:04
     1 asset
    Entrypoint main = files_mediaviewer.js
     [1] (webpack)/buildin/global.js 475 bytes {0} [built]
     [3] ./package.json 1.05 KiB {0} [built]
     [4] ./src/styles/default.scss 1.21 KiB {0} [built]
     [5] ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/lib/loader.js!./src/styles/default.scss 32.5 KiB {0} [built]
     [9] ./src/config.json 123 bytes {0} [built]
    [13] ./src/scripts/default.js + 44 modules 365 KiB {0} [built]
         | ./src/scripts/default.js 1.41 KiB [built]
         | ./src/scripts/setup.js 489 bytes [built]
         | ./src/scripts/Viewer.vue 455 bytes [built]
         | ./src/scripts/ViewerSpinner.vue 476 bytes [built]
         | ./src/scripts/helper.js 847 bytes [built]
         | ./src/scripts/store.js 2.81 KiB [built]
         | ./src/scripts/ie11routerfix.js 498 bytes [built]
         | ./src/scripts/Viewer.vue?vue&type=template&id=a1675122& 204 bytes [built]
         | ./src/scripts/Viewer.vue?vue&type=script&lang=js& 350 bytes [built]
         | ./src/scripts/ViewerSpinner.vue?vue&type=template&id=50f46259& 211 bytes [built]
         | ./src/scripts/ViewerSpinner.vue?vue&type=script&lang=js& 364 bytes [built]
         | ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./src/scripts/Viewer.vue?vue&type=template&id=a1675122& 1.19 KiB [built]
         | ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/scripts/Viewer.vue?vue&type=script&lang=js& 5.83 KiB [built]
         | ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./src/scripts/ViewerSpinner.vue?vue&type=template&id=50f46259& 371 bytes [built]
         | ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/scripts/ViewerSpinner.vue?vue&type=script&lang=js& 52 bytes [built]
         |     + 30 hidden modules
        + 8 hidden modules

    ERROR in ./src/scripts/ViewerControlsVideo.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/scripts/ViewerControlsVideo.vue?vue&type=script&lang=js&)
    Module not found: Error: Can't resolve './geteventlisteners' in '/mnt/data/apps/files_mediaviewer/src/scripts'
     @ ./src/scripts/ViewerControlsVideo.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/scripts/ViewerControlsVideo.vue?vue&type=script&lang=js&) 28:0-29
     @ ./src/scripts/ViewerControlsVideo.vue?vue&type=script&lang=js&
     @ ./src/scripts/ViewerControlsVideo.vue
     @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/scripts/ViewerControls.vue?vue&type=script&lang=js&
     @ ./src/scripts/ViewerControls.vue?vue&type=script&lang=js&
     @ ./src/scripts/ViewerControls.vue
     @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/scripts/Viewer.vue?vue&type=script&lang=js&
     @ ./src/scripts/Viewer.vue?vue&type=script&lang=js&
     @ ./src/scripts/Viewer.vue
     @ ./src/scripts/default.js
```

**Comment by felixheidecke** [comment]
> **Module not found: Error: Can't resolve './geteventlisteners'** I guess geteventlisteners is case Sensitive

Indeed it is. Fixed it :-) Pls retry.

**Comment by DeepDiver1975** [comment]
> Indeed it is. Fixed it :-) @davitol pls retry.

@felixheidecke your mac is still using case insensitive filesystem? :see_no_evil:

**Comment by felixheidecke** [comment]
> @felixheidecke your mac is still using case insensitive filesystem? 🙈

Funny how it even lets you do that :-P I guess I chose wrong back in the day.

Bildschirmfoto 2019-08-19 um 11 46 01

**Comment by felixheidecke** [comment]
@davitol can I get a go here? ;-)

**Comment by felixheidecke** [comment]
Wops … Forgot that `make dist` ist still a thing ;-)

@davitol fixed it 😄 :+1:

**Pull request merged**
