### PR TITLE
Update config.json to support mimetype video/quicktime

### PR DESCRIPTION
**Pull request by mmattel**
Fixes https://github.com/owncloud/files_mediaviewer/issues/169 Add Support for playing Apple Quicktime (*.mov)

### CODE REVIEW

**Comment by mmattel** [comment]
@DeepDiver1975 mind to review

**Comment by DeepDiver1975** [comment]
@mmattel did you test this? Does it work?

It doesn't for me - using Chromium 79 and Chrome 80
In FF it works.

Half baked solutions are :hankey:

**Comment by mmattel** [comment]
There is no "one fits all" solution especially for for QT, as the implementation is very dependent on browsers. You have correctly identified this with your finding. You can easily double check this with https://browserspy.dk/quicktime.php to see if your browser supports it or not.
This PR is good for those browsers who have implemented support. Therefore proposing to merge.

**Comment by mmattel** [comment]
@DeepDiver1975 @felixheidecke ping, would be great if it could make it into the new release...

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 @felixheidecke ping, would be great if it could make it into the new release...

:-1: from my pov - this is a shitty user experiance

**Comment by mmattel** [comment]
You know, and I have written, that QT is dependent on if its support is implemented in the browser.
There is nothing we can do to change that. A browser might get a push up by using a addon to support it. Again nothing we can do. But for all the Apple users (macOS and IOS) this PR helps, as the support is in Safari. The refrenced issue is describing that. So what is the point of denying?

**Comment by mmattel** [comment]
This is just a note:

A possible solution could be to identify via JS if the browser is capable of playing a particular format.
```
var hasVideo = !!document.createElement('video').canPlayType &&
               !!document.createElement('video').canPlayType('video/mp4')
```
Where `video/mp4` is replaced by a variable containing the found and enabled video format.

**Comment by mmattel** [comment]
Added code to check if a video mimetype is playable by the browser.

This leads to following (wanted) behavior:
- If playable - register the mime, and play in browser
- If not playable, do not register, video will be downloaded (browser standard).

Tests made with sample videos from https://file-examples.com/index.php/

For an additional test, I removed mp4 from the mime list.
After compiling, mp4 was as expected downloaded and not played.

@DeepDiver1975 pls recheck

**Pull request merged**
