### PR TITLE
Add fullscreen functionality

### PR DESCRIPTION
**Pull request by felixheidecke**
- [x] Fullscreen for video-playback
- [ ] Pause swiper on fullscreen

## Broser support
- [x] Google Chrome Support
- [x] Firefox Support
- [x] MS Edge Support

## Testplan

- [x] TEST: Swiping left/right on touch enabled devices
- [x] TEST: MS Edge

### CODE REVIEW

**Comment by PVince81** [comment]
Works in Firefox.

But:
- [ ] missing video controls in fullscreen mode

sounds like this will be more work...

**Comment by felixheidecke** [comment]
All right, I added in more stuff and tested on FF and Chrome. I can't really test on funky touch devices, but remove the "pull/push resistance" on slides in hopes of smoother swiping.

**Comment by PVince81** [comment]
large play button is good enough for now. would be good to also have a big pause button later on that appears only on focus (like on mobile). added to the other ticket: https://github.com/owncloud/files_mediaviewer/issues/27#issuecomment-467480074

**Comment by PVince81** [comment]
fullscreen mode seems to work fine.
looks like these are native html5 controls? that's fine for now

**Comment by PVince81** [comment]
- [ ] minor bug: when swiping a video, the arrow stays in place. it should probably disappear or following

**Comment by felixheidecke** [comment]
> looks like these are native html5 controls?

Yes, it's an actual `document.requestFullscreen()` and default controls get enabled. We could write our own fullscreen using vw/vh on a high z-index.

@PVince81 I tested MS Edge and checked off the arrow bug on swipe.

**Comment by PVince81** [comment]
@felixheidecke already postponed, see https://github.com/owncloud/files_mediaviewer/pull/45#issuecomment-467480230

**Comment by PVince81** [comment]
ah, the swiper, not the pause button... then please raise as ticket

**Comment by PVince81** [comment]
@felixheidecke please merge after raising tickets for outstanding tasks

**Pull request merged**
